variable "resource_group_name" {}
variable "location" {}
variable "vnet_name" {}
variable "vnet_address_space" {}
variable "web_subnet_name" {}
variable "web_subnet_address_prefixes" {}
variable "db_subnet_name" {}
variable "db_subnet_address_prefixes" {}
variable "service_plan_name" {}
variable "app_service_sku" {}
variable "os_type" {}
variable "webapp_name" {}
variable "always_on" {}
variable "app_settings" {}
variable "sql_server_name" {}
variable "sql_version" {}
variable "administrator_login" {}
variable "administrator_login_password" {}
variable "minimum_tls_version" {}
variable "sql_database_name" {}
variable "sku_name" {}
variable "storage_account_name" {}
variable "account_tier" {}
variable "account_replication_type" {}
variable "container_name" {}
variable "container_access_type" {}
